### ISSUE TITLE
 Issue publishing to Tableau Server Online using the Clickhouse JDBC by ANALYTIKA PLUS connector

### ISSUE THREAD

**Issue by fengpann98** [analytikaplus/clickhouse-tableau-connector-jdbc#28]
Hello!

I have both the [clickhouse-jdbc-0.3.2-patch2-shaded.jar] driver and ANALYTIKA PLUS connector installed and stored at the designated places on my MacOS. I am able to connect to it on my Tableau Desktop, however, the issue here is I can't publish it to Tableau server online. 
<img width="378" alt="Screen Shot 2022-02-02 at 1 11 53 PM" src="https://user-images.githubusercontent.com/87501011/152238103-5558542c-b3e6-4311-923b-59cb6bf6e457.png">

* Both the driver and connector are the latest version. 
* Stored in the designated places according to the instructions in https://clickhouse.com/learn/lessons/connect-tableau-to-clickhouse/

**Comment by artshevchenko** [comment]
Hi!

Unfortunately, Tableau Online is not supported now. You can use this connector only with Tableau Desktop, Tableau Prep Builder and Tableau Server. If you look at the connector installation process on Tableau Server, you will notice that you need to install the connector and install the driver. Both of these actions cannot be performed on Tableau Online, since this is a modified Tableau Server installation fully administered by Tableau engineers. In other words, there is no driver and connector on Tableau Online (and will not appear in the near future). If you need maximum flexibility in connecting to data sources and much more, then you will have to deploy Tableau Server.
